server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

app:
  scheduler:
    person:
      enable: true
      start: "0 */1 * * * *"
      stop: "0 */30 * * * *"
    refresh:
      cron: "0 */1 * * * *"
  kafka:
    person:
      topic: person.topic
  wiremock:
    url: https://8vyeq.wiremockapi.cloud
  test:
    name: ">>>>>>>>>>>>> mudei via properties do config server <<<<<<<<<<<<<<<"

logging:
  level:
    com:
      vitu:
        spring:
          dynamic:
            consumer:
              client: DEBUG

spring:
  kafka:
    bootstrap-servers: 192.168.0.140:30094
    listener:
      ack-mode: manual
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full